### ISSUE TITLE
Phoenix 1.7 controllers broken when plug_http_cache

### ISSUE THREAD

**Issue by niccolox** [tanguilp/plug_http_cache#4]
When I edit and update an existing schema in a controller I get the error below

just started happening when I installed 

```
      # https://github.com/tanguilp/plug_http_cache_demo/blob/disk-backend/mix.exs
      {:http_cache, "~> 0.3.0"},
      {:plug_http_cache, "~> 0.3.0"},
      {:http_cache_store_disk, "~> 0.3.0"},
      {:plug_cache_control, "~> 1.1.0", github: "tanguilp/plug_cache_control"}
```

Phoenix 1.7
elixir 1.14.5-otp-26
erlang 26.2

mix.exs

```
  defp deps do
    [
      {:bandit, "~> 1.1"},
      {:bcrypt_elixir, "~> 3.1"},
      {:cachex, "~> 3.6"},
      {:ecto_enum, "~> 1.4"},
      {:ecto_sql, "~> 3.11"},
      {:ecto_psql_extras, "~> 0.7.14"},
      {:esbuild, "~> 0.8.1"},
      {:jason, "~> 1.4"},
      {:libcluster, "~> 3.3"},
      {:number, "~> 1.0"},
      {:postgrex, ">= 0.0.0"},
      {:phoenix, "~> 1.7"},
      {:phoenix_ecto, "~> 4.4"},
      {:phoenix_html, "~> 3.3"},
      {:phoenix_html_simplified_helpers, "~> 2.1"},
      {:phoenix_live_reload, "~> 1.4.1", only: :dev},
      {:phoenix_live_view, "~> 0.20.1"},
      {:phoenix_live_dashboard, "~> 0.8.3"},
      {:phoenix_markdown, "~> 1.0"},
      {:phoenix_view, "~> 2.0"},
      {:tailwind, "~> 0.2.0"},
      {:telemetry_metrics, "~> 0.6"},
      {:telemetry_poller, "~> 1.0"},
      {:timex, "~> 3.7"},
      # https://github.com/tanguilp/plug_http_cache_demo/blob/disk-backend/mix.exs
      {:http_cache, "~> 0.3.0"},
      {:plug_http_cache, "~> 0.3.0"},
      {:http_cache_store_disk, "~> 0.3.0"},
      {:plug_cache_control, "~> 1.1.0", github: "tanguilp/plug_cache_control"},
    ]
  end
```

```
MatchError at PUT /channels/2/posts/3
no match of right hand side value: %{path: "/p/3-free-1"}
# MatchError at PUT /channels/2/posts/3

Exception:

    ** (MatchError) no match of right hand side value: %{path: "/p/3-free-1"}
        (http_cache 0.3.0) [/home/niccolox/Projects/folkbot.app/deps/http_cache/src/http_cache.erl](http://local.folkbot.com:4000/channels/2/posts/3):826: :http_cache.url_digest/2
        (http_cache 0.3.0) /home/niccolox/Projects/folkbot.app/deps/http_cache/src/http_cache.erl:1184: :http_cache.handle_invalidation_of_unsafe_method/3
        (http_cache 0.3.0) /home/niccolox/Projects/folkbot.app/deps/http_cache/src/http_cache.erl:675: :http_cache.analyze_cache/3
        (http_cache 0.3.0) /home/niccolox/Projects/folkbot.app/deps/http_cache/src/http_cache.erl:601: :http_cache.cache/3
        (plug_http_cache 0.3.1) lib/plug_http_cache.ex:285: PlugHTTPCache.cache_response/2
        (elixir 1.14.5) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
        (plug 1.15.2) lib/plug/conn.ex:1836: Plug.Conn.run_before_send/2
        (plug 1.15.2) lib/plug/conn.ex:441: Plug.Conn.send_resp/1
        (folkbot 0.1.7) lib/folkbot_web/controllers/post_controller.ex:1: FolkbotWeb.PostController.action/2
        (folkbot 0.1.7) lib/folkbot_web/controllers/post_controller.ex:1: FolkbotWeb.PostController.phoenix_controller_pipeline/2
        (phoenix 1.7.10) lib/phoenix/router.ex:432: Phoenix.Router.__call__/5
        (folkbot 0.1.7) lib/folkbot_web/endpoint.ex:1: FolkbotWeb.Endpoint.plug_builder_call/2
        (folkbot 0.1.7) deps/plug/lib/plug/debugger.ex:136: FolkbotWeb.Endpoint."call (overridable 3)"/2
        (folkbot 0.1.7) lib/folkbot_web/endpoint.ex:1: FolkbotWeb.Endpoint.call/2
        (phoenix 1.7.10) lib/phoenix/endpoint/sync_code_reload_plug.ex:22: Phoenix.Endpoint.SyncCodeReloadPlug.do_call/4
        (bandit 1.1.1) lib/bandit/pipeline.ex:101: Bandit.Pipeline.call_plug/2
        (bandit 1.1.1) lib/bandit/pipeline.ex:22: Bandit.Pipeline.run/6
        (bandit 1.1.1) lib/bandit/http1/handler.ex:31: Bandit.HTTP1.Handler.handle_data/3
        (bandit 1.1.1) lib/bandit/delegating_handler.ex:18: Bandit.DelegatingHandler.handle_data/3
        (bandit 1.1.1) /home/niccolox/Projects/folkbot.app/deps/thousand_island/lib/thousand_island/handler.ex:369: Bandit.DelegatingHandler.handle_info/2
    

Code:

`/home/niccolox/Projects/folkbot.app/deps/http_cache/src/http_cache.erl`

    821       crypto:hash(sha256,
    822                   <<MethodDigest/binary, UrlDigest/binary, BodyDigest/binary, BucketDigest/binary>>).
    823   
    824   url_digest(Url, Opts) ->
    825       NormUrl = uri_string:normalize(Url),
    826>      #{host := Host, path := Path} = ParsedUrl = uri_string:parse(NormUrl),
    827       NormQuery = normalize_query(ParsedUrl, Opts),
    828       BucketDigest = crypto:hash(sha256, erlang:term_to_binary(map_get(bucket, Opts))),
    829       crypto:hash(sha256, <<Host/binary, Path/binary, NormQuery/binary, BucketDigest/binary>>).
    830   
    831   normalize_query(#{query := Query}, #{ignore_query_params_order := true}) ->
    
`/home/niccolox/Projects/folkbot.app/deps/http_cache/src/http_cache.erl`

    1179   handle_invalidation_of_unsafe_method(Request,
    1180                                        [{HeaderName, HeaderValue} | RestHeaders],
    1181                                        #{store := Store, store_opts := StoreOpts} = Opts) ->
    1182       case ?LOWER(HeaderName) of
    1183           <<"location">> ->
    1184>              Store:invalidate_url(url_digest(HeaderValue, Opts), StoreOpts);
    1185           <<"content-location">> ->
    1186               Store:invalidate_url(url_digest(HeaderValue, Opts), StoreOpts);
    1187           _ ->
    1188               ok
    1189       end,
    
`/home/niccolox/Projects/folkbot.app/deps/http_cache/src/http_cache.erl`

    670                          <<"pragma">>,
    671                          <<"vary">>]),
    672       % A POST request that triggers invalidation cannot be cacheable
    673       case must_invalidate_request_uri(Request, Response, ParsedRespHeaders) of
    674           true ->
    675>              handle_invalidation_of_unsafe_method(Request, RespHeaders, Opts),
    676               telemetry_set_metadata(cacheable, false),
    677               not_cacheable;
    678           false ->
    679               ParsedReqHeaders =
    680                   parse_headers(ReqHeaders,
    
`/home/niccolox/Projects/folkbot.app/deps/http_cache/src/http_cache.erl`

    596   %%------------------------------------------------------------------------------
    597   
    598   -spec cache(request(), response(), opts()) -> {ok, response()} | not_cacheable.
    599   cache(Request, Response, Opts) ->
    600       telemetry_start_measurement(total_time),
    601>      Result = do_cache(Request, Response, init_opts(Opts)),
    602       telemetry_stop_measurement(total_time),
    603       telemetry_send_event(?TELEMETRY_CACHE_EVT),
    604       Result.
    605   
    606   do_cache({<<"HEAD">>, _, _, _} = Request, {200, _, _} = Response, NormOpts) ->
    
`lib/plug_http_cache.ex`

    280   
    281     defp cache_response(%Plug.Conn{state: :set} = conn, opts) do
    282       alt_keys = alt_keys(conn)
    283       http_cache_opts = Map.put(opts, :alternate_keys, alt_keys)
    284   
    285>      case :http_cache.cache(request(conn), response(conn), http_cache_opts) do
    286         {:ok, _} ->
    287           # We can't use the response returned by :http_cache because Plug disallow changing
    288           # a response that is already :set
    289           conn
    290   
    
`lib/enum.ex`

    No code available.

`lib/plug/conn.ex`

    1831     end
    1832   
    1833     ## Helpers
    1834   
    1835     defp run_before_send(%Conn{private: private} = conn, new) do
    1836>      conn = Enum.reduce(private[:before_send] || [], %{conn | state: new}, & &1.(&2))
    1837   
    1838       if conn.state != new do
    1839         raise ArgumentError, "cannot send/change response from run_before_send callback"
    1840       end
    1841   
    
`lib/plug/conn.ex`

    436     def send_resp(%Conn{state: :unset}) do
    437       raise ArgumentError, "cannot send a response that was not set"
    438     end
    439   
    440     def send_resp(%Conn{adapter: {adapter, payload}, state: :set, owner: owner} = conn) do
    441>      conn = run_before_send(conn, :set)
    442   
    443       {:ok, body, payload} =
    444         adapter.send_resp(payload, conn.status, conn.resp_headers, conn.resp_body)
    445   
    446       send(owner, @already_sent)
    
`lib/folkbot_web/controllers/post_controller.ex`

    1>  defmodule FolkbotWeb.PostController do
    2     use FolkbotWeb, :controller
    3   
    4   
    5     alias Folkbot.Channels
    6     alias Folkbot.Channels.Post
    
`lib/folkbot_web/controllers/post_controller.ex`

    1>  defmodule FolkbotWeb.PostController do
    2     use FolkbotWeb, :controller
    3   
    4   
    5     alias Folkbot.Channels
    6     alias Folkbot.Channels.Post
    
`lib/phoenix/router.ex`

    427           :telemetry.execute([:phoenix, :router_dispatch, :stop], measurements, metadata)
    428           halted_conn
    429   
    430         %Plug.Conn{} = piped_conn ->
    431           try do
    432>            plug.call(piped_conn, plug.init(opts))
    433           else
    434             conn ->
    435               measurements = %{duration: System.monotonic_time() - start}
    436               metadata = %{metadata | conn: conn}
    437               :telemetry.execute([:phoenix, :router_dispatch, :stop], measurements, metadata)
    
`lib/folkbot_web/endpoint.ex`

    1>  defmodule FolkbotWeb.Endpoint do
    2     use Phoenix.Endpoint, otp_app: :folkbot
    3   #  use SiteEncrypt.Phoenix
    4   
    5     # @site_encrypt :folkbot
    6     #               |> Application.compile_env(FolkbotWeb.Endpoint)
    
`deps/plug/lib/plug/debugger.ex`

    131             case conn do
    132               %Plug.Conn{path_info: ["__plug__", "debugger", "action"], method: "POST"} ->
    133                 Plug.Debugger.run_action(conn)
    134   
    135               %Plug.Conn{} ->
    136>                super(conn, opts)
    137             end
    138           rescue
    139             e in Plug.Conn.WrapperError ->
    140               %{conn: conn, kind: kind, reason: reason, stack: stack} = e
    141               Plug.Debugger.__catch__(conn, kind, reason, stack, @plug_debugger)
    
`lib/folkbot_web/endpoint.ex`

    1>  defmodule FolkbotWeb.Endpoint do
    2     use Phoenix.Endpoint, otp_app: :folkbot
    3   #  use SiteEncrypt.Phoenix
    4   
    5     # @site_encrypt :folkbot
    6     #               |> Application.compile_env(FolkbotWeb.Endpoint)
    
`lib/phoenix/endpoint/sync_code_reload_plug.ex`

    17   
    18     def call(conn, {endpoint, opts}), do: do_call(conn, endpoint, opts, true)
    19   
    20     defp do_call(conn, endpoint, opts, retry?) do
    21       try do
    22>        endpoint.call(conn, opts)
    23       rescue
    24         exception in [UndefinedFunctionError] ->
    25           case exception do
    26             %UndefinedFunctionError{module: ^endpoint} when retry? ->
    27               # Sync with the code reloader and retry once
    
`lib/bandit/pipeline.ex`

    96       end
    97     end
    98   
    99     @spec call_plug(Plug.Conn.t(), plug_def()) :: Plug.Conn.t() | no_return()
    100     defp call_plug(%Plug.Conn{} = conn, {plug, plug_opts}) when is_atom(plug) do
    101>      case plug.call(conn, plug_opts) do
    102         %Plug.Conn{} = conn -> conn
    103         other -> raise("Expected #{plug}.call/2 to return %Plug.Conn{} but got: #{inspect(other)}")
    104       end
    105     end
    106   
    
`lib/bandit/pipeline.ex`

    17             Plug.Conn.headers(),
    18             plug_def()
    19           ) :: {:ok, Plug.Conn.t()} | {:ok, :websocket, Plug.Conn.t(), tuple()} | {:error, term()}
    20     def run(req, transport_info, method, request_target, headers, plug) do
    21       with {:ok, conn} <- build_conn(req, transport_info, method, request_target, headers),
    22>           conn <- call_plug(conn, plug),
    23            {:ok, :no_upgrade} <- maybe_upgrade(conn) do
    24         {:ok, commit_response(conn)}
    25       end
    26     end
    27   
    
`lib/bandit/http1/handler.ex`

    26         try do
    27           with {:ok, headers, req} <- Bandit.HTTP1.Adapter.read_headers(req),
    28                {:ok, :no_upgrade} <-
    29                  maybe_upgrade_h2c(state, req, transport_info, req.method, request_target, headers),
    30                {:ok, %Plug.Conn{adapter: {Bandit.HTTP1.Adapter, req}} = conn} <-
    31>                 Bandit.Pipeline.run(
    32                    {Bandit.HTTP1.Adapter, req},
    33                    transport_info,
    34                    req.method,
    35                    request_target,
    36                    headers,
    
`lib/bandit/delegating_handler.ex`

    13       |> handle_bandit_continuation(socket)
    14     end
    15   
    16     @impl ThousandIsland.Handler
    17     def handle_data(data, socket, %{handler_module: handler_module} = state) do
    18>      handler_module.handle_data(data, socket, state)
    19       |> handle_bandit_continuation(socket)
    20     end
    21   
    22     @impl ThousandIsland.Handler
    23     def handle_shutdown(socket, %{handler_module: handler_module} = state) do
    
`/home/niccolox/Projects/folkbot.app/deps/thousand_island/lib/thousand_island/handler.ex`

    364               {%ThousandIsland.Socket{socket: raw_socket} = socket, state}
    365             )
    366             when msg in [:tcp, :ssl] do
    367           ThousandIsland.Telemetry.untimed_span_event(socket.span, :async_recv, %{data: data})
    368   
    369>          __MODULE__.handle_data(data, socket, state)
    370           |> handle_continuation(socket)
    371         end
    372   
    373         def handle_info(
    374               {msg, raw_socket},
    

## Connection details

### Params

    %{"_csrf_token" => "NDgRAS4XB28ANDxBGDA7LjllFRoddFAAnNbkBYD_gkNqaJdHkRpsz9ek", "_method" => "put", "channel_id" => "2", "id" => "3", "post" => %{"body" => "guest Free Subtitle", "channel_id" => "2", "contact_id" => nil, "creator_id" => nil, "is_featured?" => "false", "is_free?" => "false", "is_invitable?" => "false", "is_listed?" => "false", "is_premium?" => "false", "is_previewable?" => "false", "is_private?" => "false", "is_published?" => "false", "owner_id" => nil, "page_layout" => "show", "position" => "0", "slug" => "free-1", "subtitle" => "guest Free Subtitle", "summary" => nil, "title" => "guest Free Post", "user_id" => "1", "video" => nil, "website_id" => "1"}}

### Request info

  * URI: http://local.folkbot.com:4000/channels/2/posts/3
  * Query string: 

### Headers
  
  * accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8
  * accept-encoding: gzip, deflate
  * accept-language: en-US,en;q=0.9
  * cache-control: max-age=0
  * connection: keep-alive
  * content-length: 2951
  * content-type: multipart/form-data; boundary=----WebKitFormBoundaryhXOGBbrTSjIVwyzr
  * cookie: _folkbot_web_user_remember_me=SFMyNTY.g2gDbQAAACCGMWSF2zz3VEsPoS2KkOXQHD3tJBmGMLH2s6_cJJy5X24GANsxIXqMAWIATxoA.olKxk9T4K2aHJ10NKHFjLShEp8OgAUBo5XeIbUlsZNU; _cookie_key=XCP.xoPIMjSQIKTwc20DfgONTVugFIWBXphmE21QY-Wu76eapoGGSnXis4x7EGrcU38R69PhF5L55nbDGqBdvc_BfkU1Lp5drskVkqK6nGdLPqioYcTyYINtBIi6tS3iBFW2Eehx5rKs3sgq8STKrg8wbh1hlHmv1S11KYKVXPXnHSIxRP40Bkg7msdBtt0rFZS-V1wce2yObm5MmAHBmdcIUsDJEKMa913738QpIC_4Bw8tfEAsoPToumNXzZnnDxCBSysgmEuqSGC23A1-Uqtap4s1ZK9PsrvbAhAvLL9Ck2eIXFQBlz1UZbyiIefjn6XPdP9eM0Do_xng81f8HGjt7tGAk7Rea5K_Yz0hXIRDAoUHEIT3qzoYbU3rdWtWrfOzDuTrzab51BbpXseBGCGPsvhsbCbItMOkezSpyEPn7qa14b085eh_jTqh6RNhvT9lkRYy0Cob9fRDXPGa3jgnkZd3ZTG7c0JzuWvRwmbjHhPGlZ_cxTEojAjrVNFwhAb3Zh5cgtB-BI9iCorGrT4GbvVdnqrWfGHkJ_h8bPSl-HfUOHFbA12srqgzURQyM8nrqgLdZkp8NDW3mFWuVbKYGjc0Np4cPJGalVUyuZYolZTvXbPrt63L-Bmu9QN-utWrKkwhtpChjOnzcyL9JSd4mOweiK9QvXoRJR3XNB6UGsiM55cPEjRLU_1p3fZI9MMqgrrgBnhedXw6-pL2X35wLJUdJ0pD8Mmc-9r_rxFciR0dm3Quv3Vzp5vdGvZO6UrmjF2BRN9uZpoy0A8P1TZ1TznwCx9kZu_V4ZUw-GTjrCV3f7pg_qOW_XMso8_sG-38OQ4Vmhg_q0C0Oi9CGHOgLgSqE4nfeaVbdNU7LCgo4eBZTQAjgX8nM-7RU1167_n0AU6Zu_AkZiYBAK_e_FmDfutebPBFnGC_ZhqNDnAgSyx3PAvPxpoK5mZvE_1l7gugs7zWfPpIbTG-J4KVEAz39KvmKcmqPeUkNZzQr5TKEx6Jrm1Gi9jcVuXC_fVk1s4Tkz0ULalK9-sso8od4Sly7WvAkoH8rFPqUXM-fIAV0KFIyJ3PXQzjasm7bQsQ6crFH4OAUlR64aMUv5qO7d81VcCAicIabZruEJ3okO_pc4yxKpN2ywmUDw6L6IkeNaiTHcKbt_snvVb_JYV21fa-kxR7prt41AHGnm5Vk5ia1V32hyWDvWlHzE_e4M5bP_q6lUvIHJqtCu0ikELruxJPOh9lo6DjR3LV72bEgBX6YKAPs0Dv5TDhTgrH81D6yEIXktaVN9msGHFbljj6RF0DHYzLPZ0yzQ
  * host: local.folkbot.com:4000
  * origin: http://local.folkbot.com:4000
  * referer: http://local.folkbot.com:4000/channels/2/posts/3/edit
  * sec-gpc: 1
  * upgrade-insecure-requests: 1
  * user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36

### Session

    %{"_csrf_token" => "ZvsjlNC0g_r0yz_fR7eigM5k", "_navigation_history_default" => "/channels/2/posts/3/edit", "current_user_id" => 1, "is_admin?" => true, "live_socket_id" => "users_sessions:hjFkhds891RLD6EtipDl0Bw97SQZhjCx9rOv3CScuV8=", "user_token" => <<134, 49, 100, 133, 219, 60, 247, 84, 75, 15, 161, 45, 138, 144, 229, 208, 28, 61, 237, 36, 25, 134, 48, 177, 246, 179, 175, 220, 36, 156, 185, 95>>, "website_domain" => "folkbot.com", "website_id" => 1, "website_rich_title" => "Folkbot: platform for the people", "website_slug" => "folkbot", "website_theme_accent_color_hsl" => "144 43% 42%", "website_theme_base_100_color_hsl" => "240 4% 95%", "website_theme_daisyui_animation_btn" => "0.25s", "website_theme_error_color_hsl" => "350 72% 64%", "website_theme_info_color_hsl" => "221 63% 56%", "website_theme_neutral_color_hsl" => "278 29% 16%", "website_theme_primary_color_hsl" => "118 84% 27%", "website_theme_secondary_color_hsl" => "30 66% 59%", "website_theme_success_color_hsl" => "157 80% 34%", "website_theme_warning_color_hsl" => "47 96% 44%"}

/home/niccolox/Projects/folkbot.app/deps/http_cache/src/http_cache.erl
    crypto:hash(sha256,
                <<MethodDigest/binary, UrlDigest/binary, BodyDigest/binary, BucketDigest/binary>>).
url_digest(Url, Opts) ->
    NormUrl = uri_string:normalize(Url),
    #{host := Host, path := Path} = ParsedUrl = uri_string:parse(NormUrl),
    NormQuery = normalize_query(ParsedUrl, Opts),
    BucketDigest = crypto:hash(sha256, erlang:term_to_binary(map_get(bucket, Opts))),
    crypto:hash(sha256, <<Host/binary, Path/binary, NormQuery/binary, BucketDigest/binary>>).
normalize_query(#{query := Query}, #{ignore_query_params_order := true}) ->
```

**Comment by niccolox** [comment]
closing, awareness issue on my behalf related to how these 4 or 5 modules work together

resolved by router.ex

```
  pipeline :cache_responses do
    plug PlugHTTPCache, Application.get_env(:folkbot, :plug_http_cache_opts)
  end

    scope "/" do
      pipe_through :cache_responses
      get "/", PageController, :index
    end
```

and controller limit to :index action

```
  plug PlugCacheControl, [directives: [:public, s_maxage: 60 * 20], replace: true] when action == :index
  def index(conn, _params) do
```

closing
